int(1)
int(1).add(int(1))
int(1).addInt(int(1))
int(1).asFloat()
int(1).asInt()
int(1).asString()
int(1).isInt()
int(1).negated()
int(1).to(int(9))

int(1).to(int(3)).append(int(4).to(int(6)))
int(1).to(int(9)).at(int(3))
int(1).to(int(9)).negated()

float(1).isFloat()
float(2).rand()
float(2).rand(float(3))
float(3).rand2()
float(3.14159).sin().negated()
