fetch-osc:
	wget https://unpkg.com/osc@2.4.2/dist/osc-browser.js

clone-scsynth:
	git clone https://gitlab.com/rd--/scsynth-wasm-builds

fetch-scsynth:
	(cd scsynth-wasm-builds ; git pull)

fetch-ace:
	(cd ace-builds ; git pull)

clone-ace:
	git clone https://github.com/ajaxorg/ace-builds/
