fetch-ace:
	(cd ace-builds ; git pull)

clone-ace:
	git clone https://github.com/ajaxorg/ace-builds/

clone-oscjs:
	git clone https://github.com/colinbdclark/osc.js/

fetch-oscjs:
	(cd osc.js ; git pull)

clone-scsynth:
	git clone https://gitlab.com/rd--/scsynth-wasm-builds

fetch-scsynth:
	(cd scsynth-wasm-builds ; git pull)

fetch-quill:
	rm -Rf quill
	wget https://github.com/quilljs/quill/releases/download/v1.3.7/quill.tar.gz
	tar zxf quill.tar.gz
	rm quill.tar.gz

